---

name: localdb

services:
  redis:
    annotations:
      io.wgames.role: database
      io.wgames.name: redis
      io.wgames.flavour: redis
      io.wgames.project: localdb
    image: "redis"
    ports:
      - "6379:6379"
  ext:
    annotations:
      io.wgames.role: database
      io.wgames.flavour: postgres
      io.wgames.name: ext
      io.wgames.project: localdb
    build:
      context: ./ext/
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg-ext
        target: /var/lib/postgresql
      - type: bind
        source: ./ext/scripts
        target: /scripts
    environment:
      POSTGRES_USER: wg
      POSTGRES_PASSWORD: wg
      POSTGRES_DB: wg
  conf:
    annotations:
      io.wgames.role: database
      io.wgames.flavour: postgres
      io.wgames.name: conf
      io.wgames.project: localdb
    build:
      context: ./conf/
    ports:
      - "5434:5432"
    volumes:
      - type: volume
        source: pg-conf
        target: /var/lib/postgresql
      - type: bind
        source: ./conf/scripts
        target: /scripts
    environment:
      POSTGRES_USER: wg
      POSTGRES_PASSWORD: wg
      POSTGRES_DB: wg

volumes:
  pg-ext:
  pg-conf:
