---

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  ext:
    build:
      context: ./ext/
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg-ext
        target: /var/lib/postgresql
    environment:
      POSTGRES_USER: wg
      POSTGRES_PASSWORD: wg
      POSTGRES_DB: wg
  conf:
    build:
      context: ./ext/
    ports:
      - "5434:5432"
    volumes:
      - type: volume
        source: pg-conf
        target: /var/lib/postgresql
    environment:
      POSTGRES_USER: wg
      POSTGRES_PASSWORD: wg
      POSTGRES_DB: wg

volumes:
  pg-ext:
  pg-conf:
